layout_spectrum: 0.7688634687651059
typography_spectrum: 0.7035927393565895
color:
  brandColors:
    - '#181818'
    - '#AD150C'
    - '#FFFFFF'
    - '#461714'
    - '#343434'
  brandStrength: 0.44493512504346816
  lightness: 0.06090070769172346
  saturation: 0.9854501559640659
  rhythmicContrast: 0.06349129426136317
content_rating:
  adult: false
name: m
url: 'http://grid.maauer.com/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: /
    url: 'https://maauer.com'
    type: external
title: Site Title
content: []
description: Description
github: true
