layout_spectrum: 0.8618189742027016
typography_spectrum: 0.6223409058432104
color:
  brandColors:
    - '#303807'
    - '#FFFFFF'
    - '#C4B687'
    - '#636E20'
    - '#CED5DF'
  brandStrength: 0.825734285129935
  lightness: 0.5263682697704154
  saturation: 0.83356795828061
  rhythmicContrast: 0.3696084366317396
content_rating:
  adult: false
github: true
name: m
url: 'http://grid.maauer.com/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: /
    url: 'https://maauer.com'
    type: external
  - name: wd
    id: b3c2a7ce-11f0-40f1-a65a-c66b4ab75b51
    type: content
title: Chappaqua Troop 2
content: []
description: ''
