typography_spectrum: 0.45303853799745736
content_rating:
  adult: false
color:
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
  brandStrength: 0.2994899474297383
  lightness: 0.3058085416365267
  saturation: 0.3487144069262956
  rhythmicContrast: 0.11096234973833555
github: true
layout_spectrum: 0.5845976540474866
name: m
url: 'http://grid.maauer.com/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: /
    url: 'https://maauer.com'
    type: external
  - name: wd
    id: b3c2a7ce-11f0-40f1-a65a-c66b4ab75b51
    type: content
title: M; Grid
content: []
description: 'This is a Snake '
